"""Write ENU.SYN's data sections as C, so the engine needs no file at run time.

  python tools/embed_image.py [pkg/ENU.SYN] [-o src/gen/enu_data.c]

Only .rdata and .data: the recompiled code never reads .text (checked by trapping every .text page), and
.rsrc/.reloc are for Windows' loader. Trailing zeros are cut (the machine's memory starts zeroed).
The output is the vendor's data: generate it locally, never commit or publish it.
"""
import argparse
import hashlib
import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEEP = (".rdata", ".data")
MD5 = "6c39acb7c1f0f62b3cae019f45b224fc"      # Eloquence 6.1.0.2 ENU.SYN, the one the port was checked with


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image", nargs="?", default=os.path.join(ROOT, "pkg", "ENU.SYN"))
    ap.add_argument("-o", default=os.path.join(ROOT, "src", "gen", "enu_data.c"))
    a = ap.parse_args()
    d = open(a.image, "rb").read()
    md5 = hashlib.md5(d).hexdigest()
    if md5 != MD5:
        raise SystemExit("%s: MD5 %s, not the ENU.SYN the recompiled code was made from (%s)" % (a.image, md5, MD5))
    pe = struct.unpack_from("<I", d, 0x3c)[0]
    nsec = struct.unpack_from("<H", d, pe + 6)[0]
    opt = struct.unpack_from("<H", d, pe + 20)[0]
    base = struct.unpack_from("<I", d, pe + 24 + 28)[0]
    size = struct.unpack_from("<I", d, pe + 24 + 56)[0]
    out = ["/* Generated by tools/embed_image.py from ENU.SYN (MD5 %s). Vendor data: do not commit. */" % md5,
           '#include "../image.h"', ""]
    table = []
    total = 0
    for i in range(nsec):
        o = pe + 24 + opt + 40 * i
        name = d[o:o + 8].rstrip(b"\0").decode()
        vsz, va, rsz, ra = struct.unpack_from("<IIII", d, o + 8)
        if name not in KEEP:
            continue
        body = d[ra:ra + min(rsz, vsz)].rstrip(b"\0")
        sym = "sec_" + name.strip(".")
        out.append("static const uint8_t %s[%d] = {" % (sym, max(len(body), 1)))
        for k in range(0, len(body), 32):
            out.append("    " + ",".join(str(b) for b in body[k:k + 32]) + ",")
        out.append("};")
        out.append("")
        table.append("    { 0x%08xu, %du, %s }," % (base + va, len(body), sym))
        total += len(body)
    out.append("const image_section enu_sections[] = {")
    out += table
    out.append("};")
    out.append("const unsigned enu_nsections = %d;" % len(table))
    out.append("const image_info enu_info = { 0x%08xu, 0x%xu };" % (base, size))
    os.makedirs(os.path.dirname(a.o), exist_ok=True)
    open(a.o, "w", newline="\n").write("\n".join(out) + "\n")
    print("%s: %d sections, %d bytes" % (a.o, len(table), total))


if __name__ == "__main__":
    main()
