r"""prologues - the stack bytes each hand-ported function's prologue writes, as C for the ports to write too.

  python tools/prologues.py        (writes src/gen/prologues.c, from src/ported.h and ENU.SYN)

A hand port keeps its locals in C, so the scratch below the entry esp that the original leaves (and that later
code sometimes reads uninitialized: the rules copy such bytes into the heap) differs. Most of those bytes are
the prologue's: `push ebp`, `push ebx/esi/edi`, `push ecx` reserving a local - the caller's registers, which
the machine holds exactly at the port's entry (recompiled callers, and lifted rules mirror theirs). For every
address in src/ported.h the entry instructions are decoded while they are `push reg`, `mov ebp, esp` or
`sub esp, imm`; port_prologue(c, address) writes the pushed registers where the original does. PORT_FN
(src/port.h) calls it before the port's body.
"""
import os
import re
import sys

from capstone import Cs, CS_ARCH_X86, CS_MODE_32

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import x2c  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGS = {"eax", "ecx", "edx", "ebx", "esp", "ebp", "esi", "edi"}


def prologue(img, md, a):
    """[(C address expression, register)] of the pushes at the function's entry"""
    o = img.off(a)
    base, sp = "sp", 0          # esp = base - sp (base: the entry esp, or an aligned esp)
    out = []
    clobbered = set()           # registers no longer the caller's
    md.detail = True
    for x in md.disasm(img.d[o:o + 96], a):
        ops = x.op_str
        if x.mnemonic == "push" and ops in REGS and ops != "esp":
            if ops in clobbered:
                break
            sp += 4
            out.append(("%s - %d" % (base, sp), ops))
        elif x.mnemonic == "mov" and ops == "ebp, esp":
            clobbered.add("ebp")
        elif x.mnemonic == "sub" and re.match(r"^esp, (0x[0-9a-f]+|\d+)$", ops):
            sp += int(ops.split(", ")[1], 0)
        elif x.mnemonic == "and" and re.match(r"^esp, 0xfffffff[0-9a-f]$", ops):
            # an aligned frame (and esp, -8): the rest is relative to the aligned esp
            base, sp = "((%s - %d) & %su)" % (base, sp, ops.split(", ")[1]), 0
        elif x.mnemonic in ("test", "cmp"):
            continue
        elif x.mnemonic == "mov" and re.match(r"^(byte|word|dword) ptr \[esp( \+ (0x[0-9a-f]+|\d+))?\], ", ops):
            # a store into its own frame (a local the port writes itself): registers and esp unchanged
            continue
        elif x.mnemonic in ("mov", "movzx", "movsx", "xor", "lea", "and", "or", "add", "sub", "shl", "shr",
                            "sar", "inc", "dec", "neg", "not", "imul") and \
                x.operands[0].type == 1 and x.reg_name(x.operands[0].reg) != "esp":
            # a register load (x86 operand type 1 = register destination): no memory written, esp unchanged
            r = x.reg_name(x.operands[0].reg)
            full = {"al": "eax", "ax": "eax", "cl": "ecx", "cx": "ecx", "dl": "edx", "dx": "edx", "bl": "ebx",
                    "bx": "ebx", "si": "esi", "di": "edi"}.get(r, r)
            clobbered.add(full)
        else:
            break
    return out


def main():
    img = x2c.Image(os.path.join(ROOT, "pkg", "ENU.SYN"))
    md = Cs(CS_ARCH_X86, CS_MODE_32)
    addrs = [int(m, 16) for m in re.findall(r"^PORTED\(([0-9a-f]{8})", open(os.path.join(ROOT, "src", "ported.h")).read(), re.M)]
    lines = ["/* generated by tools/prologues.py from ENU.SYN: the stack bytes each hand-ported function's prologue",
             " * writes (see src/port.h). Do not edit. */",
             '#include "../x86rt.h"', "",
             "void port_prologue(cpu *c, uint32_t a)", "{", "    const uint32_t sp = c->esp;", "    switch (a) {"]
    n = 0
    for a in sorted(set(addrs)):
        p = prologue(img, md, a)
        if not p:
            continue
        n += 1
        body = " ".join("wr32(c, %s, c->%s);" % (addr, r) for addr, r in p)
        lines.append("    case 0x%08xu: %s break;" % (a, body))
    lines += ["    default: break;", "    }", "}", ""]
    out = os.path.join(ROOT, "src", "gen", "prologues.c")
    open(out, "w", newline="\n").write("\n".join(lines))
    print("prologues: %d of %d hand-ported functions push registers at entry" % (n, len(set(addrs))))


main()
